### ISSUE TITLE
Decryption for OPN, WEP and Statistics page

### ISSUE THREAD

**Issue by BenjaminPoh** [pinyoko573/SponsoredByPekoVPN#12]
The packet decryption only works for WPA/WPA2 authentication, but not for OPN and WEP (tested it).
For the statistics page, when I navigate to summary, pick a session id and go to ARP table then back to summary, the session_id in URL parameter is gone (need select the session id again)

**Comment by pinyoko573** [comment]
Updated, please review the code and app before merging
