### ISSUE TITLE
Datatable Error

### ISSUE THREAD

**Issue by BenjaminPoh** [pinyoko573/SponsoredByPekoVPN#5]
Intermittent error, happens in create and modify sessions page when loading data either from refreshing or when page loads.
 
 
 Source:
  File "/home/kali/Desktop/SponsoredByPekoVPN/app.py", line 66, in session_get_ap
    return jsonify(get_ap_list())
  File "/home/kali/Desktop/SponsoredByPekoVPN/session.py", line 111, in get_ap_list
    i['ESSID'] = i['ESSID'][:-1]
<img width="959" alt="databse eerror pic" src="https://user-images.githubusercontent.com/89081958/176608278-3e0f23e1-d45b-4753-b7a7-20d00644c8ea.png">

**Comment by pinyoko573** [comment]
This error can be produced if the adapter did not pick up any wireless channels (create session) or clients (modify session), which leads to a out of bound array exception.
I'll fix the bug and add a loader to prevent users from clicking refresh multiple times too.
