### ISSUE TITLE
Forcing handshake issue

### ISSUE THREAD

**Issue by BenjaminPoh** [pinyoko573/SponsoredByPekoVPN#9]
Sometimes, the network adapter (RTL8812BU) receives multiple EAPOL packets of the same step, causing the application to recognise as 'Successful' when the handshake is not completely captured yet.
Also, as tested during Milestone 2, the handshake capture process takes very long which we have to click the button repeatedly to get the handshake working.
![Kali-Linux-2020 4-vmware-amd64-2022-07-10-10-29-52](https://user-images.githubusercontent.com/89081958/178129942-ae478aba-00e3-4b05-aa36-d27f87f040b0.png)

**Comment by pinyoko573** [comment]
Please test out the application again on the bug_fixes branch and if okay, pull request to main
